// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNBwRtO8imP6wiO5482jxBpLNyIVJDaNE',
    appId: '1:399545037428:web:1b7f71c080cb6ea8781721',
    messagingSenderId: '399545037428',
    projectId: 'carrental-bb07f',
    authDomain: 'carrental-bb07f.firebaseapp.com',
    storageBucket: 'carrental-bb07f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD66Qn2kedYGBIhQ0weFQi8UxBJAte7VB8',
    appId: '1:399545037428:android:c1b6e5e704847c5b781721',
    messagingSenderId: '399545037428',
    projectId: 'carrental-bb07f',
    storageBucket: 'carrental-bb07f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVFvqL9Y5ZIRDOc_6n1D4HJhbdxxnql6c',
    appId: '1:399545037428:ios:e320491a55886ee7781721',
    messagingSenderId: '399545037428',
    projectId: 'carrental-bb07f',
    storageBucket: 'carrental-bb07f.appspot.com',
    iosBundleId: 'com.example.carrental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVFvqL9Y5ZIRDOc_6n1D4HJhbdxxnql6c',
    appId: '1:399545037428:ios:e320491a55886ee7781721',
    messagingSenderId: '399545037428',
    projectId: 'carrental-bb07f',
    storageBucket: 'carrental-bb07f.appspot.com',
    iosBundleId: 'com.example.carrental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNBwRtO8imP6wiO5482jxBpLNyIVJDaNE',
    appId: '1:399545037428:web:88ddf4d0f3292cb5781721',
    messagingSenderId: '399545037428',
    projectId: 'carrental-bb07f',
    authDomain: 'carrental-bb07f.firebaseapp.com',
    storageBucket: 'carrental-bb07f.appspot.com',
  );
}
